{% set name = "segmentation-models-pytorch" %}
{% set version = "0.5.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/segmentation_models_pytorch-{{ version }}.tar.gz
  sha256: cabba8aced6ef7bdcd6288dd9e1dc2840848aa819d539c455bd07aeceb2fdf96

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - efficientnet-pytorch >=0.6.1
    - huggingface_hub >=0.24
    - numpy >=1.19.3
    - pillow >=8
    - pretrainedmodels >=0.7.1
    - python >={{ python_min }}
    - pytorch >=1.8
    - six >=1.5
    - timm >=0.9
    - torchvision >=0.9
    - tqdm >=4.42.1


test:
  imports:
    - segmentation_models_pytorch
    - segmentation_models_pytorch.base
    - segmentation_models_pytorch.encoders
    - segmentation_models_pytorch.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qubvel-org/segmentation_models.pytorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image segmentation models with pre-trained backbones. PyTorch.
  doc_url: https://smp.readthedocs.io
  dev_url: https://github.com/qubvel-org/segmentation_models.pytorch

extra:
  recipe-maintainers:
    - weiji14
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - ocefpaf
