{% set name = "segmentation-models-pytorch" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segmentation_models_pytorch-{{ version }}.tar.gz
  sha256: 8fb86acb82f8783394c725eea837688f001a2500567ac7eac7a7c2a0e80c814e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not linux]

requirements:
  host:
    - pip
    - python ==3.7
  run:
    - python ==3.7
    - pytorch
    - pretrainedmodels
    - efficientnet-pytorch >=0.5.1
    - timm
    - tqdm

test:
  imports:
    - segmentation_models_pytorch
    - segmentation_models_pytorch.base
    - segmentation_models_pytorch.encoders
    - segmentation_models_pytorch.fpn
    - segmentation_models_pytorch.linknet
    - segmentation_models_pytorch.pspnet
    - segmentation_models_pytorch.unet
    - segmentation_models_pytorch.utils

about:
  home: https://github.com/qubvel/segmentation_models.pytorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image segmentation models with pre-trained backbones. PyTorch.
  dev_url: https://github.com/qubvel/segmentation_models.pytorch

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
