{% set name = "segmentation-models-pytorch" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segmentation_models_pytorch-{{ version }}.tar.gz
  sha256: 21336d59687991218ffceeefe7d461fd5269ac9342a8234e75e29c7849594111

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not linux]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pytorch
    - pretrainedmodels
    - torchvision >=0.3.0
    - efficientnet-pytorch >=0.5.1

test:
  imports:
    - segmentation_models_pytorch
    - segmentation_models_pytorch.base
    - segmentation_models_pytorch.encoders
    - segmentation_models_pytorch.fpn
    - segmentation_models_pytorch.linknet
    - segmentation_models_pytorch.pspnet
    - segmentation_models_pytorch.unet
    - segmentation_models_pytorch.utils

about:
  home: https://github.com/qubvel/segmentation_models.pytorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image segmentation models with pre-trained backbones. PyTorch.
  dev_url: https://github.com/qubvel/segmentation_models.pytorch

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
