{% set name = "segmentation-models-pytorch" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segmentation_models_pytorch-{{ version }}.tar.gz
  sha256: b3b21ab4cd26a6b2b9e7a6ed466ace6452eb26ed3c31ae491ea2d7cbb01e384b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - efficientnet-pytorch ==0.7.1
    - pillow
    - pretrainedmodels ==0.7.4
    - python >=3.6
    - timm ==0.6.12
    - torchvision >=0.5.0
    - tqdm


test:
  imports:
    - segmentation_models_pytorch
    - segmentation_models_pytorch.base
    - segmentation_models_pytorch.encoders
    - segmentation_models_pytorch.utils
  commands:
    - pip check
  requires:
    - pip
    - python <3.11

about:
  home: https://github.com/qubvel/segmentation_models.pytorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image segmentation models with pre-trained backbones. PyTorch.
  dev_url: https://github.com/qubvel/segmentation_models.pytorch

extra:
  recipe-maintainers:
    - weiji14
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - ocefpaf
